Add files via upload
Yonasle/Code_review pull request #1
Opened 2023-02-27 08:36 UTC by Yonasle

File Copied from Admission  trial

2023-02-27 09:02 UTC, Yonasle commented
Hi @Yonasle ,

Great job so far! 👏
You've done well, however, there are some issues that you still need to work on to go to the next project, but you are almost there!

-Best Practice  CSS and HTML ✔️

Required Changes ♻️
-Implement Linters
-Implement Professional README file

2023-02-27 09:25 UTC, Owusu-Desmond requested changes
Hi @Yonasle , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif"/>

## Highlights
📌 Good to perform a review✅
📌 Great working on the setup of the project ✅
📌 Good commit message ✅

## Required Changes ♻️
_Check the comments under the review._

- [ ] Please form the project requirement, you should perform a review by adding at least two inline comments using the [inline comment feature on GitHub](https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request) suggesting changes on applying HTML & CSS best practices and issues in your code. :blush:  While making these reviews, please make sure that you well-explain the reason you are suggesting the changes in a polite way. :pray:  For instance, _**Why don't you use an article tag for the .first-article element instead of a div, that would improve the HTML structure and make the page more accessible**_ :+1: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-27 11:21 UTC, leonardodiasb requested changes
# Required Changes ♻️ ⚠️ 🚦 

Hi @Yonasle, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 

 - Correct use of GitHub flow. ✔️

## Aspects to improve ♻️

- [x] Check the comments under the review.
- [ ] As the previous code reviewer suggested, please make use of the [inline comment feature on GitHub](https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request) by adding at least two inline comments as the project required, so you can start getting used to it. This is a very important feature for the Pull Requests and I'm sure you can find something that you can improve in your code. While making these reviews, please make sure that you well-explain the reason you are suggesting the changes in a polite way.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-27 11:40 UTC, Yonasle commented
@leonardodiasb  Yeah i already did it. 1. from HTML part 2.from READme.md part what is the problem then.

2023-02-27 12:50 UTC, medaminedev66 commented
Hello @Yonasle 👋,

_This is an additional review as a result of the second opinion request._

One of the project requirements is using the [GitHub inline comments feature](https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request) at least once to leave review comments. I recommend following the guides provided in the link above or watching[ this video](https://youtu.be/lSnbOtw4izI) to learn how to use inline comments, and then try to perform a new review with inline comments (at least one inline comment).

**Important**: After writing a new inline comment, instead of clicking on `add single comment`, click on `start review`.

Additionally, as requested by the previous reviewers you should work more on your comments so they are more specific, clear, polite, easy to understand, and reasonable:
- When giving feedback on an error in a pull request, adopt a constructive mindset and try to use positive language. Kindly say “I suggest” or “You could improve X by doing Y.” and avoid “Do this” or “This is just wrong, why don’t you do Z?”
- Don’t forget to provide reasons behind everything you say. For example, link to articles or docs reinforcing your point.

Keep rocking 🚀!

2023-02-27 14:06 UTC, Yonasle commented on index.html
> +    <div id="main">
-Kindly  I recommend to use a class selector. Because Reusability: Classes can be applied to multiple elements on a page, whereas IDs can only be used once. This makes classes more versatile and reusable in different contexts.

2023-02-27 14:06 UTC, Yonasle commented on README.md
> -# 📖 [your_project_name] <a name="about-project"></a>
Kindly please consider including Project Name. since a project name is to give the project a clear and concise identity that helps to differentiate it from other projects. A good project name should be unique, memorable, and reflective of the project's goals and objectives.

2023-02-27 14:33 UTC, divinecharlotte approved these changes
Hi @Yonasle , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 💯 
- Good communication with the reviewers✔️ 

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)

## Optional suggestions

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-27 14:38 UTC, merged

2023-03-27 11:07 UTC, Abenezer-Tilahun commented
Hi @Yonasle 
 
Your project is complete  👍 💯   There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 👏🏻

✔️ Good Job for phrased the comments politely and  includes an explanation
✔️ You used correct Git Hub-Flow.
✔️ Good Job for Using [GitHub inline comments feature](https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request)  
✔️ Good job for Implemented Review your project from trials!.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).